### ISSUE TITLE
AKMNs loading the tracers as default

### ISSUE THREAD

**Issue by indig0fox** [FridayNightFight/FNF#118]
Needs to have standard rounds loaded on initial loadout assignment. currently loads tracer mag.

**Comment by Mjolnir64** [comment]
Caused by both tracers and non-tracers being added to player inventory before the weapon is added, so for some weapon sets, the tracers get chosen to be the mags the weapon loads. Fixed with https://github.com/FridayNightFight/FNF/commit/2b08e5d578e114c343898f64998d125c8d2d0dd2 -- quick hack, but it's what can be done without combining the weapon and magazine add functions. This will work fine anyways.
